audio:
  delete_after_processing: true
  input_folder: AudioInbox
  max_duration_seconds: 1800
  min_duration_seconds: 5
  supported_formats:
  - .mp3
  - .wav
  - .m4a
  - .aac
  - .ogg
  - .flac

output:
  date_format: '%Y-%m-%d'
  include_audio_filename: true
  include_processing_timestamp: true
  save_transcript: true
  transcript_folder: "transcripts"

processing:
  gpt_model: gpt-4.1-mini
  weekly_summary_model: gpt-4.1
  max_tokens: 3000
  temperature: 0.4
  # Audio transcription settings
  audio_model: whisper  # Options: whisper, assembly
  # Whisper settings
  whisper_model: large-v3
  compute_type: float32  # Options: float32, float16, int8
  cpu_threads: 8
  num_workers: 8
  batch_size: 2
  beam_size: 4
  # AssemblyAI settings
  assembly_model: slam  # Options: nano, slam
  language_code: "en"

project:
  daily_notes_path: Vault/1. Projects/Daily Notes
  projects_path: Vault/1. Projects
  vault_path: Vault